name: Fútbol de robots
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: RobotSoloParado.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: RobotSoloPateando.png
    when:
      black: 0
      blue: 2
      green: 0
      red: 0
  - image: FutbolSolo.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: ArcoSolo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 1
  - image: RobotParadoYFutbol.png
    when:
      black: 1
      blue: 1
      green: 0
      red: 0
  - image: RobotPateandoYFutbol.png
    when:
      black: 1
      blue: 2
      green: 0
      red: 0
  - image: FutbolYArco.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 1
